title: Introduction to Circular Economy
description: Course materials and notes
# theme: jekyll-theme-minimal
remote_theme: pages-themes/primer@v0.6.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Markdown-Engine
markdown: kramdown

# # Navigationslinks im Header (optional)
# header_pages:
#   - index.md
#   - pages.md    # Ãœbersicht der Collection (siehe Schritt 4)

# # Deine Collection: _pages/
# collections:
#   pages:
#     output: true
#     permalink: /:collection/:name/   # ergibt /pages/dateiname/
